version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - form-net

  backend:
    build: ./form-backend
    image: form-backend-image
    container_name: form-backend-container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - form-net

  frontend:
    build: ./form-frontend
    image: form-frontend-image
    container_name: form-frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - form-net

volumes:
  mongo-data:
    external: true

networks:
  form-net:
    driver: bridge
