apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-backend
  template:
    metadata:
      labels:
        app: form-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: form-backend
          image: mharis3008/form-backend-image:latest
          ports:
            - containerPort: 5000
           
---
apiVersion: v1
kind: Service
metadata:
  name: form-backend
spec:
  type: NodePort
  selector:
    app: form-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081 

